from enum import IntEnum, auto


class AmmoType(IntEnum):
    ARROW = auto()
    BEAM = auto()
    CANNONBALL = auto()
    BULLET = auto()


AM_SPEED_D = 5
AM_SPEED_ARROW = 10
AM_SPEED_BEAM = 25
AM_SPEED_CANNONBALL = 15
AM_SPEED_BULLET = 30

AM_DAMAGE_D = 10
AM_DAMAGE_ARROW = 10
AM_DAMAGE_BEAM = 20
AM_DAMAGE_CANNONBALL = 15
AM_DAMAGE_BULLET = 25

AM_RANGE_CANNONBALL = 100


class EnemyType(IntEnum):
    TEST = auto()
    COMMON = auto()
    ARMORED = auto()
    RAPID = auto()
    BOSS = auto()


EM_REWARD_COMMON = 20
EM_REWARD_ARMORED = 50
EM_REWARD_RAPID = 50
EM_REWARD_BOSS = 500

EM_SPEED_D = 2
EM_SPEED_COMMON = 2
EM_SPEED_ARMORED = 1
EM_SPEED_RAPID = 4
EM_SPEED_BOSS = 1

EM_HP_D = 50
EM_HP_COMMON = 50
EM_HP_ARMORED = 80
EM_HP_RAPID = 30
EM_HP_BOSS = 300

EM_HP_COEF = 0.25

EM_P_DEFENCE_D = 1
EM_P_DEFENCE_COMMON = 0
EM_P_DEFENCE_ARMORED = 5
EM_P_DEFENCE_RAPID = 0
EM_P_DEFENCE_BOSS = 5

EM_M_DEFENCE_D = 5
EM_M_DEFENCE_COMMON = 0
EM_M_DEFENCE_ARMORED = 0
EM_M_DEFENCE_RAPID = 5
EM_M_DEFENCE_BOSS = 5

EM_DAMAGE_D = 10
EM_DAMAGE_COMMON = 5
EM_DAMAGE_ARMORED = 10
EM_DAMAGE_RAPID = 10
EM_DAMAGE_BOSS = 50

EM_INTERVAL_BOSS = 300
EM_BOSS_RECOVER = 100


class TowerType(IntEnum):
    BASE = 0
    TEST = auto()
    ARCHER = auto()
    CANNON = auto()
    WIZARD = auto()
    SNIPER = auto()
    MARKSMAN = auto()


TO_COST_ARCHER = 20
TO_COST_CANNON = 100
TO_COST_WIZARD = 50
TO_COST_SNIPER = 100
TO_COST_MARKSMAN = 50

TO_RANGE_D = 200
TO_RANGE_ARCHER = 100
TO_RANGE_WIZARD = 150
TO_RANGE_CANNON = 150
TO_RANGE_SNIPER = 200
TO_RANGE_MARKSMAN = 150

TO_INTERVAL_D = 30
TO_INTERVAL_ARCHER = 60
TO_INTERVAL_WIZARD = 90
TO_INTERVAL_CANNON = 150
TO_INTERVAL_SNIPER = 90
TO_INTERVAL_MARKSMAN = 20

UP_WIDTH = 20

COMMON = 10
UPGRADE = 11


class EntityType(IntEnum):
    FINISH = 200


class ButtonType(IntEnum):
    TO_DELETE = 201
    BACK = 202
    PAUSE = 203
    ENTER = 204


ME_SCALE_COEF = 2
ME_R_TIME_D = 30
WORD_SIZE = 50


class PageType(IntEnum):
    WELCOME = 0
    SELECT = auto()
    PAUSE = auto()
    CONCLUDE_WIN = auto()
    CONCLUDE_LOSE = auto()
    GAME = auto()


class SummonType(IntEnum):
    TEST = 0
    END = -1
    COMMON = auto()
    ARMORED = auto()
    RAPID = auto()
    BOSS = auto()


END = -10
REST = -12


class MapTaskType(IntEnum):
    RESET = -13
    UPDATE = -14


class GameJudge(IntEnum):
    WIN = -2
    LOSE = -1
    UNDECIDED = -3
